### ISSUE TITLE
Unable to train Burmese tokenizer for training_size = 100,000

### ISSUE THREAD

**Issue by yongzx** [bigscience-workshop/multilingual-modeling#18]

**Comment by haileyschoelkopf** [comment]
Have you been able to replicate this? I've had it happen before, but just trying again later went much faster and finished quickly.

**Comment by yongzx** [comment]
> I've had it happen before, but just trying again later went much faster and finished quickly.
Which language was this? I am debugging it right now, and have been able to replicate this bug consistently.

**Comment by haileyschoelkopf** [comment]
This was with Thai. I’ll try with Burmese

**Comment by yongzx** [comment]
Thanks Hailey! Yeap it's memory issue.
